# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20171009_2106'),
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonasHasLugares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='lugares',
            name='colonia',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='personashaslugares',
            name='lugares_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugares.Lugares'),
        ),
        migrations.AddField(
            model_name='personashaslugares',
            name='personas_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Personas'),
        ),
    ]
